j1945LibraryMS/urls.py
from django.conf.urls import url ,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('mainpage.urls',namespace='mainpage')),
]

mainpage/urls.py
from django.conf.urls import url

from . import views

app_name='[mainpage]'

urlpatterns = [
    url(r'^$', views.index, name= 'index'),
    url(r'^initPage$', views.initPage, name= 'initPage'),
     url(r'^login$', views.login, name= 'login'),
    url(r'^logon$', views.logon, name= 'logon'),
    url(r'^loginback$', views.loginback, name= 'loginback'),
    url(r'^logonback$', views.logonback, name= 'logonback'),
    url(r'^showUserMess$', views.showUserMess, name= 'showUserMess'),
    url(r'^changemess$', views.changemess, name= 'changemess'),
    url(r'^delUser$', views.delUser, name= 'delUser'),
    url(r'^outHistory$', views.outHistory, name= 'outHistory'),
    url(r'^usingBook$', views.usingBook, name= 'usingBook'),
    url(r'^getBook(.*)', views.getBook, name= 'getBook'),
    url(r'^returnBook(.*)', views.returnBook, name= 'returnBook'),
    
    
    #url(r'^download(.*)', views.download, name= 'download'),
]

    


"""

电脑上运行、连接MySQL数据库（初始100本书）
1.管理员登录。管理员个人信息（编号、姓名、性别、联系方式、住址），管理图书信息。
2.(这个不需要了)馆藏图书检索。读者需要根据键入词及检索方式检索所需结果。检索结果呈现格式有书目详细信息（图书编号、书名、作者、内容简介、主题、出版社、）、馆内流通信息（索书号、登录号、典藏部门、应还期限）
3.个人信息查询。读者输入用户名及密码，登录个人中心。账号信息（用户编号、用户姓名、性别、住址、到期时间、用户类型）、借书信息（图书编号、典藏部门、流通状态、应还期限、续借）、借阅历史等
4.借书信息。显示读者所借阅图书的详细信息，书名、图书编号典藏部门、流通状态、应还日期及需要续借的功能，时长默认一个月。
借阅历史。显示读者借阅历史。包括书名、图书编号、类型（借书or还书）和更改日期
5.个性化图书推荐。利用读者借阅图书信息、检索图书信息，向读者推荐相似图书。

"""

mainpage/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

# Create your models here.

# python manage.py makemigrations mainpage
# python manage.py migrate mainpage

class userMessage(models.Model):  #
    userName= models.CharField(max_length=32)   #帐号
    passWord = models.CharField(max_length = 32)    #密码
    realName = models.CharField(max_length=32)   #姓名
    sex = models.CharField(max_length=5)       #性别
    userClass=models.CharField(max_length = 32)    #用户类别（管理员or读者）
    callMeth = models.EmailField(max_length = 32)    #邮箱--
    address= models.CharField(max_length = 50)  #地址

    
class bookMessage(models.Model):  #
    bookCode = models.IntegerField(primary_key=True)   #图书编号
    bookName = models.CharField(max_length = 50)    #书名
    bookClass=models.CharField(max_length = 32)    #图书类别
    whereIs = models.CharField(max_length = 32)    #典藏部门
    status = models.CharField(max_length=32)   #流通状态
    outTime = models.IntegerField(default = 30) #应还期限

    
class history(models.Model):
    hisId=models.IntegerField(primary_key=True )#id
    userName=models.CharField(max_length=32)   #借阅人
    bookCode = models.IntegerField(default = 0)   #图书编号
    bookName = models.CharField(max_length = 50)    #书名
    activeClass=models.CharField(max_length = 25)    #类型（借书or还书）
    activeTime = models.DateTimeField(auto_now =True) #更改日期
    
    
"""
电脑上运行、连接MySQL数据库（初始100本书）
1.管理员登录。管理员个人信息（编号、姓名、性别、联系方式、住址），管理图书信息。
2.(这个不需要了)馆藏图书检索。读者需要根据键入词及检索方式检索所需结果。检索结果呈现格式有书目详细信息（图书编号、书名、作者、内容简介、主题、出版社、）、馆内流通信息（索书号、登录号、典藏部门、应还期限）
3.个人信息查询。读者输入用户名及密码，登录个人中心。账号信息（用户编号、用户姓名、性别、住址、到期时间、用户类型）、借书信息（图书编号、典藏部门、流通状态、应还期限、续借）、借阅历史等
4.借书信息。显示读者所借阅图书的详细信息，书名、图书编号典藏部门、流通状态、应还日期及需要续借的功能，时长默认一个月。
借阅历史。显示读者借阅历史。包括书名、图书编号、类型（借书or还书）和更改日期
5.个性化图书推荐。利用读者借阅图书信息、检索图书信息，向读者推荐相似图书。
"""

mainpage/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render_to_response

from  django.conf import settings
from mainpage.models import userMessage  
from mainpage.models import bookMessage  
from mainpage.models import history  

import os
import random

# Create your views here.


def index(request):     #设置cookies  
    response= render_to_response('index.html') 
    if "user_cookie"  not in request.COOKIES or 'user_name' not in request.COOKIES:
        strlist="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789"
        usermess=''
        for i in range(20):
            usermess=usermess+strlist[random.randint(0,len(strlist)-1)]
        #print(usermess)
        response.set_cookie('user_cookie',usermess,365*24*60*60*1)#设置
        response.set_cookie('user_name',bytes("登录", 'utf-8').decode('ISO-8859-1'),365*24*60*60*1)#设置用户名
    return response  

def initBooks():
    books=bookMessage.objects.all().values('bookCode') 
    if not books.exists():
        readBookToSQL() #初始化书籍


def readBookToSQL():    #读取图书到数据库
    booksfile= open(os.path.join(settings.BASE_DIR, "books.txt"), 'r')
    bookclass=""
    flag=0
    for line in booksfile:
        if len(line.strip())>1:
            if  line.strip()=="####":
                flag=1
            elif flag==1:
                bookclass=line.strip()
                flag=0
            else :
                pro=bookMessage.objects.create( #存入数据库
                    bookName = line.strip(),   #书名
                    bookClass=bookclass ,   #图书类别
                    whereIs = "本部门",   #典藏部门
                    status = "在馆",   #流通状态
                    outTime = 30, #应还期限
                )
                #print(line.strip(),bookclass)
                #pro.save()
    booksfile.close()
def getAllBooks():
    books=bookMessage.objects.all().values_list('bookCode','bookName','bookClass','whereIs','status','outTime') 
    #print(books)
    
    return books
    
def initPage(request):    
    
    initBooks()
    #return HttpResponse("hello")
    context=dict(
        errormessage="",
        uname=bytes(request.COOKIES["user_name"], 'ISO-8859-1').decode('utf-8'),
        books=getAllBooks(),
    )
    response= render_to_response('initPage.html',context) 
    return response  
    
def login(request):
    return render_to_response('login.html')
def logon(request):
    return render_to_response('logon.html')
    
from django.views.decorators.csrf import csrf_exempt	#这两句是让下面的函数接受form表单的上传文件不会出CSRF的错误，在html 的form中加一句 {% csrf_token %}

@csrf_exempt
def logonback(request):  #注册
    uname=request.POST['username']
    pword=request.POST['password']   
    if 'logon' in request.POST:     #注册 
        if len(uname)<4 or len(pword)<4 :
            context={
                'errormessage':"用户名或密码长度不能小于等于4！",
                }
            return render_to_response('logon.html',context)
   
        if userMessage.objects.filter(userName=uname).count()>0:
            context={
            'errormessage':"用户名已注册！",
            }
            response= render_to_response('logon.html',context) 
            return response #注册失败'denglu'.encode('utf-8')
        
        #注册成功
        print(request.POST['sex'] )
        pro=userMessage.objects.create(#存入数据库
			userName = uname,
			passWord = pword,
			realName = request.POST['realname']   ,  #姓名
            sex = request.POST['sex']      ,   #性别
            userClass="读者"   ,  #用户类别（管理员or读者）
            callMeth =request.POST['email']    ,  #邮箱--
            address=request.POST['address']   , #地址
		)
        #pro.save()
        response= render_to_response('login.html')
        return response
    
@csrf_exempt
def loginback(request):     #登录
    uName=request.POST['username']
    pWord=request.POST['password']
    if len(uName)<1 or len(pWord)<1 :
        return render_to_response('login.html')
    umess = userMessage.objects.filter(userName=uName).values_list("passWord")
    for data in umess:
        if  pWord==data[0]:
            #return HttpResponse("helloworld")
            context=dict(
                uname=uName,
                errormessage="",
                books=getAllBooks(),
            )
            response= render_to_response('initPage.html',context) 
            response.set_cookie('user_name',bytes(uName, 'utf-8').decode('ISO-8859-1'),24*60*60)#设置用户名,1天
            #return HttpResponse("helloworld")
            return response #登录成功
    
    #登录失败 
    context={
    'errormessage':"用户名或密码错误请重新输入！",
    }
    response= render_to_response('login.html',context)
    return response
    
def showUserMess(request):
    uname=bytes(request.COOKIES["user_name"], 'ISO-8859-1').decode('utf-8')
    selfmess=userMessage.objects.filter(userName=uname).values_list("userName","passWord","realName","sex","userClass","callMeth","address")
    context=dict(
    errormessage="",
    selfMess=list(selfmess)[0],
    )
    return render_to_response('selfmess.html',context)
  
@csrf_exempt  
def changemess(request):
    uname=bytes(request.COOKIES["user_name"], 'ISO-8859-1').decode('utf-8')
    userMessage.objects.filter(userName=uname).update(userName=request.POST['username'],passWord=request.POST['password'],realName=request.POST['realname'],sex=request.POST['sex'],callMeth=request.POST['email'],address=request.POST['address'])
    selfmess=userMessage.objects.filter(userName=uname).values_list("userName","passWord","realName","sex","userClass","callMeth","address")
    context=dict(
        errormessage="保存成功",
        selfMess=list(selfmess)[0],
    )
    return render_to_response('selfmess.html',context)
   
   
def delUser(request):
    context=dict(
        errormessage="",
        uname="登录",
        books=getAllBooks(),
    )
    response= render_to_response('initPage.html',context) 
    response.set_cookie('user_name',bytes("登录", 'utf-8').decode('ISO-8859-1'),365*24*60*60*1)#设置用户名
    return response  
    
def outHistory(request):
    uname=bytes(request.COOKIES["user_name"], 'ISO-8859-1').decode('utf-8')
    outhistory=history.objects.filter(userName=uname).values_list("userName","bookCode","bookName","activeClass","activeTime")
    if outhistory.exists():
        outhistory=list(outhistory)
        tempHistory=[]
        for k in outhistory:
            temp=list(k)
            temp[4]=temp[4].strftime('%y-%m-%d %I:%M:%S %p')
            if temp[3]!="在借中":
                tempHistory.append(temp)
        outhistory=tempHistory
        print(outhistory)
        
    else:
        outhistory=""
    context=dict(
        errormessage="",
        outHistory=outhistory,
    )
    return render_to_response('outHistory.html',context)
    
def usingBook(request):
    uname=bytes(request.COOKIES["user_name"], 'ISO-8859-1').decode('utf-8')
    outhistory=history.objects.filter(userName=uname,).values_list("userName","bookCode","bookName","activeClass","activeTime")
    if outhistory.exists():
        outhistory=list(outhistory)
        tempHistory=[]
        for k in outhistory:
            temp=list(k)
            temp[4]=temp[4].strftime('%y-%m-%d %I:%M:%S %p')
            if temp[3]=="在借中":
                tempHistory.append(temp)
        outhistory=tempHistory
        print(outhistory)
        
    else:
        outhistory=""
    context=dict(
        errormessage="",
        outHistory=outhistory,
    )
    return render_to_response('usingBook.html',context)
    
def getBook(request ,bcode):
    uname=bytes(request.COOKIES["user_name"], 'ISO-8859-1').decode('utf-8')
    if history.objects.filter(userName=uname,activeClass="在借中").count()<20 and uname!="登录":
        books=bookMessage.objects.filter(bookCode=bcode).values_list('status') 

        emessage=""
        if books.exists() and list(list(books)[0])[0]=="在馆":
            bookMessage.objects.filter(bookCode=bcode).update(status="外借")
            pro=history.objects.create(#存入数据库
			    userName=uname,   #借阅人
                bookCode = bcode,   #图书编号
                bookName = list(list(bookMessage.objects.filter(bookCode=bcode).values_list('bookName'))[0])[0],    #书名
                activeClass="借书",
		    )
            #pro.save()
            pro=history.objects.create(#存入数据库
			    userName=uname,   #借阅人
                bookCode = bcode,   #图书编号
                bookName = list(list(bookMessage.objects.filter(bookCode=bcode).values_list('bookName'))[0])[0],    #书名
                activeClass="在借中",
		    )
            #pro.save()
        
        else:
            emessage="该书已借出，请借阅其他图书"
    elif uname=="登录":
            emessage="请先登录"
    else:
        emessage="你的借书数量超过20,请还书后再借"
    context=dict(
    errormessage=emessage,
    uname=bytes(request.COOKIES["user_name"], 'ISO-8859-1').decode('utf-8'),
    books=getAllBooks(),
    )
    response= render_to_response('initPage.html',context) 
    return response
def returnBook(request ,bcode):
    uname=bytes(request.COOKIES["user_name"], 'ISO-8859-1').decode('utf-8')
    bookMessage.objects.filter(bookCode=bcode).update(status="在馆")
    books=history.objects.filter(userName=uname,bookCode=bcode,activeClass="在借中").update(activeClass="还书")

    return usingBook(request)
    
    

mainpage/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    {% load staticfiles %}

    <title>初始化</title>

</head>

<body>
<span class="logo"> </span>
<br><br><br><br>
    <div id="nav_bar"></div>
    <div id="footer"></div>

<script>

window.location.href="{% url 'mainpage:initPage' %}";
</script>
</body>

</html>





 

mainpage/templates/initPage.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

 {% load staticfiles %}
<title>图书借阅系统</title>
 <meta charset= "utf-8">
 
<link href="{% static 'css/mycss.css' %}" type="text/css" rel="stylesheet" />
<script src="{% static 'js/test.js' %}"></script>
</head>

<body style="background: url({% static 'images/bj1.gif' %}) ;">

<div  id="menu">
    <a  id="menu1" href="{% url 'mainpage:initPage' %}" style="left:30%;">全部图书</a>
    <a  id="menu1" href="{% url 'mainpage:initPage' %}" style="left:45%;">个性推荐</a>
    <a  id="menu1" href="{% url 'mainpage:outHistory' %}" style="left:60%;">借阅记录</a>
    
    <ul class=menu2-ul>
        <li>
            <a  id="menu2" onmouseover="isLogin(this);" onclick="isLoginbeenClicked(this);">{{uname}}</a>
            <ul id="menu-select" onclick="menuSMouseOut(this);">
                  <li><a onmouseout="stopBubble(this);" href="{% url 'mainpage:showUserMess' %}">个人信息</a></li>
                  <li><a onmouseout="stopBubble(this);" href="{% url 'mainpage:usingBook' %}">在借图书</a></li>
                  <li><a onmouseout="stopBubble(this);" href="{% url 'mainpage:delUser' %}">注销账户</a></li>
            </ul>
        </li>
    </ul>
    
</div>
<script>
if(document.getElementById("menu2").innerHTML!="登录")
    {
        document.getElementById("menu2").innerHTML="用户："+document.getElementById("menu2").innerHTML;
        
    }
    else{
        document.getElementById("menu2").innerHTML="登录"
    }
    if("{{errormessage}}"!="")
    alert("{{errormessage}}");
</script>

    <div id="books">
    
        <script>

            {% for j in books %}        
               
               var filestyle="<div class='fatherbook' id='BOOK{{j.0}}' onmouseover=bookmouseover('BOOK'+{{j.0}},'{{j.4}}'); onmouseout=bookMouseOut('BOOK'+{{j.0}});>\
               <div id='otherBOOK{{j.0}}' class='usebook' >\
                <a id='booktipsBOOK{{j.0}}' class='booktips' href={% url 'mainpage:getBook' j.0 %}>借阅</a>\
               </div>\
               <div class='book' >\
               <img src={% static 'images/book.jpg' %} width='100%' height='100%' /><br>\
               <div  class='case'>编号：{{j.0}}</div>\
               <div  class='case'>书名：{{j.1}}</div>\
               <div  class='case'>类别：{{j.2}}</div>\
               <div  class='case'>典藏部门：{{j.3}}</div>\
               <div  class='case'>在馆状态：{{j.4}}</div>\
               <div  class='case'>归还期限：{{j.5}}天</div>\
               </div></div>"
                document.writeln(filestyle);
                
                
               
            {% endfor %}  

        </script>

    </div>


</body>
</html>

mainpage/templates/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

 {% load staticfiles %} 
 <meta charset= "utf-8">
<title>登录</title>

<link href="{% static 'css/test.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'js/test.js' %}"></script>


</head>

<body>
    <form  class="smart-green" name="frm" action="{% url 'mainpage:loginback' %}" method="post"  title="登陆" enctype="multipart/form-data">	
            {% csrf_token %}
        <h1>登录 
            <span>请输入帐号和密码</span>
        </h1>
        <label>
            <span>用户名 :</span>
            <input id="name" type="text" name="username" maxlength="25" placeholder="Your userName" />
        </label>
        <label>
            <span>密码 :</span>
            <input id="email" type="password" name="password"  maxlength="25" placeholder="password" />
        </label>


        <label>
            <span>&nbsp;</span>
            <input type="submit" name="login" style="margin:0px 30% 0px 0px;" class="button" value="登录" />

        </label>
        <span style="font: 10px Arial, Helvetica, sans-serif; color:#5E0000; margin:0px  0px 0px 30%;">{{errormessage}}</span>
        <a href="{% url 'mainpage:logon' %}" style="font: 15px Arial, Helvetica, sans-serif; color:#5E5E5E; margin:0px  0px 0px 90%;">注册</a>
    </form>

</body>
</html>

mainpage/templates/logon.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

 {% load staticfiles %}
  <meta charset= "utf-8">
<title>注册</title>

<link href="{% static 'css/test.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'js/test.js' %}"></script>

</head>

<body>

        <form class="smart-green"  name="frm" action="logonback" method="post"  title="注册" enctype="multipart/form-data">	
        {% csrf_token %}
	        <h1>注册 
            <span>请输入注册所需信息</span>
        </h1>
        <label>
            <span>帐号 :</span>
            <input id="name" type="text" name="username" maxlength="25" placeholder="Your userName" />
        </label>
        <label>
            <span>姓名 :</span>
            <input id="name" type="text" name="realname" maxlength="25" placeholder="Your userName" />
        </label>
        <label>
            <span>密码 :</span>
            <input id="password" type="password" name="password"  maxlength="25" placeholder="password" />
        </label>
         <label>
            <span>性别 :</span>
            <select id="sex" name="sex">
                <option id="男" value="男">男</option>
                <option id="女" value="女">女</option>
            </select>
        </label>
        <label>
            <span>邮箱 :</span>
            <input id="email" type="email" name="email" maxlength="30" placeholder="Valid Email Address" />
        </label>
        <label>
            <span>地址 :</span>
            <textarea id="message" name="address" maxlength="45" placeholder="Your Address "></textarea>
        </label>
       
        <label>
            <span>&nbsp;</span>
            <input type="submit" name="logon" style="margin:0px 30% 0px 0px;" class="button" value="提交" />

        </label>
        <span style="font: 10px Arial, Helvetica, sans-serif; color:#5E0000; margin:0px  0px 0px 30%;">{{errormessage}}</span>
   
    </form>


</body>
</html>

mainpage/templates/outHistory.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

 {% load staticfiles %}
<title>图书借阅记录</title>
 <meta charset= "utf-8">
 
<link href="{% static 'css/mycss.css' %}" type="text/css" rel="stylesheet" />
<script src="{% static 'js/test.js' %}"></script>
</head>

<body style="background: #a9adc6 ;">


    <table id="historyTable">
    <caption style="background: #2b3478 ; height:30px;color:#fff">借还记录</caption> 
        <tr style="background: #5c6399 ;color:#fff">
            <th width="150px">图书编号</th><th width="150px">书名</th><th width="150px">操作</th><th width="150px">日期</th>
        </tr>
        <script>
            {% for j in outHistory %}        
               var filestyle="<tr style='background: #96a5d3 ;padding:0px;'>\
                    <td>{{j.1}}</td>\
                    <td>{{j.2}}</td>\
                    <td>{{j.3}}</td>\
                    <td>{{j.4}}</td>\
                    </tr>"
                document.writeln(filestyle);

            {% endfor %}  
        </script>
        
    </table>
</body>
</html>

mainpage/templates/selfmess.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

 {% load staticfiles %}
  <meta charset= "utf-8">
<title>注册</title>

<link href="{% static 'css/test.css' %}" rel="stylesheet" type="text/css" />
<script src="{% static 'js/test.js' %}"></script>

</head>

<body>

        <form class="smart-green"  name="frm" action="changemess" method="post"  title="注册" enctype="multipart/form-data">	
        {% csrf_token %}
	        <h1>个人信息 
            <span>如要修改请在编辑后保存</span>
        </h1>
        <label>
            <span>帐号 :</span>
            <input id="name" type="text" name="username" maxlength="25" placeholder="Your userName" value="{{selfMess.0}}"/>
        </label>
        <label>
            <span>姓名 :</span>
            <input id="name" type="text" name="realname" maxlength="25" placeholder="Your userName" value="{{selfMess.1}}"/>
        </label>
        <label>
            <span>密码 :</span>
            <input id="password" type="password" name="password"  maxlength="25" placeholder="password" value="{{selfMess.2}}"/>
        </label>
         <label>
            <span>性别 :</span>
            <select id="sex" name="sex">
                <option id="男" value="男">男</option>
                <option id="女" value="女">女</option>
            </select>
        </label>
        <label>
            <span>邮箱 :</span>
            <input id="email" type="email" name="email" maxlength="30" placeholder="Valid Email Address" value="{{selfMess.5}}"/>
        </label>
        <label>
            <span>地址 :</span>
            <textarea id="message" name="address" maxlength="45" placeholder="Your Address " >{{selfMess.6}}</textarea>
        </label>
       
        <label>
            <span>&nbsp;</span>
            <input type="submit" name="logon" style="margin:0px 30% 0px 0px;" class="button" value="保存" />

        </label>
        <span style="font: 10px Arial, Helvetica, sans-serif; color:#5E0000; margin:0px  0px 0px 30%;">{{errormessage}}</span>
   
    </form>


</body>
</html>

mainpage/templates/usingBook.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

 {% load staticfiles %}
<title>在借图书</title>
 <meta charset= "utf-8">
 
<link href="{% static 'css/mycss.css' %}" type="text/css" rel="stylesheet" />
<script src="{% static 'js/test.js' %}"></script>
</head>

<body style="background: #a9adc6 ;">


    <table id="historyTable">
    <caption style="background: #2b3478 ; height:30px;color:#fff">在借图书</caption> 
        <tr style="background: #5c6399 ;color:#fff">
            <th width="150px">图书编号</th><th width="150px">书名</th><th width="150px">日期</th><th width="150px">请操作</th>
        </tr>
        <script>
            {% for j in outHistory %}        
               var filestyle="<tr style='background: #96a5d3 ;padding:0px;'>\
                    <td>{{j.1}}</td>\
                    <td>{{j.2}}</td>\
                    <td>{{j.4}}</td>\
                    <td><a href={% url 'mainpage:returnBook' j.1 %}>还书</a></td>\
                    </tr>"
                document.writeln(filestyle);

            {% endfor %}  
        </script>
        
    </table>
</body>
</html>